export const APP_VERSION = "0.41.0";

export const ESSENTIAL_APP_PATHS = Object.freeze([
  "./",
  "index.html",
  "css/style.css",
  "css/base.css",
  "css/structured-articles.css",
  "css/favorites.css",
  "css/article-media.css",
  "css/tools.css",
  "css/article-components.css",
  "css/pwa.css",
  "css/atlas.css",
  "css/sections.css",
  "css/references.css",
  "css/pipeline-joints.css",
  "css/vibration.css",
  "css/vibration-diagnostic.css",
  "css/vibration-calculators.css",
  "css/vibration-journal.css",
  "css/vibration-data-analysis.css",
  "js/app.js",
  "js/atlas.js",
  "js/config.js",
  "js/dom.js",
  "js/favorites.js",
  "js/html.js",
  "js/imageViewer.js",
  "js/pwa.js",
  "js/pwaConfig.js",
  "js/pwaPolicy.js",
  "js/pipelineJoints.js",
  "js/references.js",
  "js/renderers.js",
  "js/ringWeld.js",
  "js/router.js",
  "js/schema.js",
  "js/search.js",
  "js/searchCore.js",
  "js/store.js",
  "js/tools.js",
  "js/vibration.js",
  "js/vibrationDiagnosticAssistant.js",
  "js/vibrationDiagnosticEngine.js",
  "js/vibrationDiagnosticQuestions.js",
  "js/vibrationDiagnosticRules.js",
  "js/vibrationDiagnosticStorage.js",
  "js/vibrationCalculations.js",
  "js/vibrationCalculatorData.js",
  "js/vibrationCalculatorStorage.js",
  "js/vibrationCalculators.js",
  "js/vibrationJournalCore.js",
  "js/vibrationJournalDb.js",
  "js/vibrationJournalChart.js",
  "js/vibrationJournal.js",
  "js/vibrationDataCore.js",
  "js/vibrationDataChart.js",
  "js/vibrationDataAnalysis.js",
  "js/vibrationKnowledge.js",
  "js/vibrationRelations.js",
  "js/vibrationTaxonomy.js",
  "js/vibrationTemplates.js",
  "js/views.js",
  "manifest.json",
  "data/vik.json",
  "data/uzk.json",
  "data/pvk.json",
  "data/rk.json",
  "data/vibration.json",
  "data/references.json",
  "data/pipeline-welded-joints.json"
]);

const PVK_INDICATION_IMAGE_SLUGS = Object.freeze([
  "linear-crack",
  "branched-crack",
  "microcrack-cluster",
  "fatigue-concentrator",
  "grinding-thermal-crack",
  "surface-incomplete-penetration",
  "surface-lack-of-fusion",
  "open-pore",
  "pore-cluster",
  "pinhole",
  "overlay-boundary",
  "scratch",
  "roughness",
  "geometric-edge",
  "thread-groove-hole",
  "loose-joint",
  "scale",
  "contamination",
  "coating-residue",
  "porous-surface",
  "weld-spatter",
  "insufficient-cleaning",
  "excess-penetrant",
  "overcleaning",
  "thick-developer",
  "uneven-developer",
  "short-dwell",
  "overdrying",
  "lint",
  "incompatible-materials",
  "insufficient-lighting"
]);

const VIBRATION_FAULT_IMAGE_SLUGS = Object.freeze([
  "unbalance", "parallel-misalignment", "angular-misalignment", "bent-shaft",
  "mechanical-looseness", "loose-bearing-housing", "bearing-clearance", "soft-foot",
  "uneven-supports", "inclined-foundation", "casing-deformation", "pipe-strain",
  "rub", "resonance", "cavitation", "surge", "gears", "motor-electrical",
  "rotor-cage", "lubrication", "bearing-outer-race", "bearing-inner-race",
  "bearing-rolling-elements", "bearing-cage", "rotor-precession", "oil-whirl",
  "babbitt", "oil-coking", "journal-bearing-misalignment"
]);

const VIBRATION_SPECTRUM_IMAGE_SLUGS = Object.freeze([
  "1x", "2x", "1x-2x", "harmonic-series", "half", "third", "oil-whirl",
  "broadband-noise", "blade-pass", "gear-mesh", "sidebands", "bpfo", "bpfi",
  "bsf", "ftf", "resonance", "clipping", "impulse", "modulated", "cavitation"
]);

export const OPTIONAL_APP_PATHS = Object.freeze([
  "images/pvk-atlas/true-indications-cover.jpg",
  "images/pvk-atlas/nonrelevant-indications-cover.jpg",
  "images/pvk-atlas/process-errors-cover.jpg",
  ...PVK_INDICATION_IMAGE_SLUGS.flatMap(slug => [
    `images/pvk-atlas/indications/${slug}-white.jpg`,
    `images/pvk-atlas/indications/${slug}-uv.jpg`,
    `images/pvk-atlas/indications/${slug}-diagram.jpg`
  ]),
  ...VIBRATION_FAULT_IMAGE_SLUGS.flatMap(slug => [
    `images/vibration-atlas/faults/${slug}-photo.jpg`,
    `images/vibration-atlas/faults/${slug}-mechanism.jpg`,
    `images/vibration-atlas/faults/${slug}-spectrum.svg`,
    `images/vibration-atlas/faults/${slug}-evidence.svg`
  ]),
  ...VIBRATION_SPECTRUM_IMAGE_SLUGS.flatMap(slug => [
    `images/vibration-atlas/spectra/${slug}-spectrum.svg`,
    `images/vibration-atlas/spectra/${slug}-diagram.svg`
  ]),
  "images/articles/vibration/source-data/typical-pump-unit.jpg",
  "images/articles/vibration/source-data/source-data-diagram.jpg",
  "images/articles/vibration/source-data/source-data-reference-table.jpg",
  "icons/icon-192.png",
  "icons/icon-512.png",
  "icons/apple-touch-icon.png",
  "images/articles/uzk/echo-pulse-principle.webp",
  "images/articles/uzk/pep-overview.webp",
  "images/articles/uzk/dac-vrc-comparison.webp",
  "images/articles/uzk/beam-input.webp",
  "images/articles/uzk/beam-zones.webp",
  "images/articles/uzk/dead-zone.webp",
  "images/defects/undercut.jpg",
  "images/defects/porosity.webp",
  "images/defects/cracks.webp",
  "images/defects/lack-of-fusion.webp",
  "images/defects/slag-inclusions.webp",
  "images/defects/unfilled-crater.webp",
  "images/defects/burn-through.webp",
  "images/defects/overlap.webp",
  "images/defects/edge-misalignment.webp",
  "images/defects/uneven-reinforcement.webp",
  "images/defects/interpass-depression.webp",
  "images/defects/metal-spatter.webp",
  "images/defects/fistula.webp",
  "images/atlas/cracks-photo.webp",
  "images/atlas/cracks-scheme.webp",
  "images/atlas/edge-misalignment-photo.webp",
  "images/atlas/edge-misalignment-scheme.webp",
  "images/atlas/fistula-photo.webp",
  "images/atlas/fistula-scheme.webp",
  "images/atlas/interpass-depression-photo.webp",
  "images/atlas/interpass-depression-scheme.webp",
  "images/atlas/lack-of-fusion-photo.webp",
  "images/atlas/lack-of-fusion-scheme.webp",
  "images/atlas/metal-spatter-photo.webp",
  "images/atlas/metal-spatter-scheme.webp",
  "images/atlas/porosity-photo.webp",
  "images/atlas/porosity-scheme.webp",
  "images/atlas/slag-inclusions-photo.webp",
  "images/atlas/slag-inclusions-scheme.webp",
  "images/atlas/uneven-reinforcement-photo.webp",
  "images/atlas/uneven-reinforcement-scheme.webp",
  "images/atlas/unfilled-crater-photo.webp",
  "images/atlas/unfilled-crater-scheme.webp"
]);

export const APP_PATHS = Object.freeze([
  ...ESSENTIAL_APP_PATHS,
  ...OPTIONAL_APP_PATHS
]);
