import { formatCalculation } from "./vibrationCalculations.js";

export function renderTrendChart(measurements, events = [], options = {}) {
  if (measurements.length < 2) return `<div class="journal-empty">Для построения тренда требуется не менее двух измерений одного параметра в сопоставимых условиях.</div>`;
  const width = 720; const height = 300; const pad = { left: 58, right: 18, top: 24, bottom: 48 };
  const sorted = [...measurements].sort((a, b) => new Date(a.measuredAt) - new Date(b.measuredAt));
  const times = sorted.map(item => new Date(item.measuredAt).getTime()); const values = sorted.map(item => Number(item.normalizedValue ?? item.value));
  const minTime = Math.min(...times); const maxTime = Math.max(...times); const minValue = Math.min(...values); const maxValue = Math.max(...values); const valueSpan = maxValue - minValue || Math.max(Math.abs(maxValue), 1) * 0.1;
  const x = time => pad.left + (time - minTime) / (maxTime - minTime || 1) * (width - pad.left - pad.right);
  const y = value => height - pad.bottom - (value - (minValue - valueSpan * 0.08)) / (valueSpan * 1.16) * (height - pad.top - pad.bottom);
  const path = sorted.map((item, index) => `${index ? "L" : "M"}${x(new Date(item.measuredAt).getTime()).toFixed(1)},${y(Number(item.normalizedValue ?? item.value)).toFixed(1)}`).join(" ");
  const visibleEvents = options.showEvents === false ? [] : events.filter(event => { const time = new Date(event.occurredAt).getTime(); return time >= minTime && time <= maxTime; });
  return `<div class="journal-chart-scroll" tabindex="0" aria-label="Прокручиваемый график тренда"><svg class="journal-chart" viewBox="0 0 ${width} ${height}" role="img" aria-labelledby="trend-chart-title trend-chart-desc"><title id="trend-chart-title">Тренд ${sorted[0].parameter}</title><desc id="trend-chart-desc">Значение изменилось с ${formatCalculation(values[0])} до ${formatCalculation(values.at(-1))} за ${values.length} измерений.</desc><line x1="${pad.left}" y1="${height - pad.bottom}" x2="${width - pad.right}" y2="${height - pad.bottom}" class="chart-axis"/><line x1="${pad.left}" y1="${pad.top}" x2="${pad.left}" y2="${height - pad.bottom}" class="chart-axis"/><text x="8" y="${pad.top + 6}" class="chart-label">${formatCalculation(maxValue)}</text><text x="8" y="${height - pad.bottom}" class="chart-label">${formatCalculation(minValue)}</text>${visibleEvents.map(event => `<g><line x1="${x(new Date(event.occurredAt).getTime())}" y1="${pad.top}" x2="${x(new Date(event.occurredAt).getTime())}" y2="${height - pad.bottom}" class="chart-event"/><text x="${x(new Date(event.occurredAt).getTime()) + 4}" y="${pad.top + 12}" class="chart-event-label">${String(event.title || event.eventType).slice(0, 24)}</text></g>`).join("")}<path d="${path}" class="chart-line"/>${sorted.map((item, index) => `<circle cx="${x(times[index])}" cy="${y(values[index])}" r="6" class="chart-point" tabindex="0"><title>${new Date(item.measuredAt).toLocaleString("ru-RU")}: ${formatCalculation(values[index])} ${item.normalizedUnit || item.unit}</title></circle>`).join("")}</svg></div><p class="journal-chart-description">За выбранный период значение изменилось с ${formatCalculation(values[0])} до ${formatCalculation(values.at(-1))} при ${values.length} измерениях.</p>`;
}
