const SOURCE = Object.freeze([{ document: "ГОСТ Р ИСО 13373-3-2016", section: "Приложение А" }]);
const condition = (field, values, weight = 1, required = false) => Object.freeze({ field, values, weight, required });
const rule = (id, faultId, label, conditions, requiredChecks, relatedSpectra = [], warnings = []) => Object.freeze({
  id, possibleFaults: Object.freeze([{ id: faultId, label }]), conditions: Object.freeze(conditions),
  weight: 2, requiredChecks: Object.freeze(requiredChecks), warnings: Object.freeze(warnings),
  relatedArticles: Object.freeze([]), relatedSpectra: Object.freeze(relatedSpectra), source: SOURCE
});

export const DIAGNOSTIC_RULES = Object.freeze([
  rule("unbalance-1x", "vibration-fault-unbalance", "Дисбаланс", [condition("frequencies", ["dominant-1x"], 4), condition("signs", ["one-x"], 2), condition("direction", ["horizontal", "vertical"], 2), condition("additional", ["radial-phase-same"], 3)], ["Сравнить радиальную фазу на опорах", "Проверить разгон и выбег", "Исключить резонанс"], ["vibration-spectrum-1x"]),
  rule("misalignment", "vibration-fault-parallel-misalignment", "Параллельная несоосность", [condition("frequencies", ["one-two-x", "dominant-2x"], 4), condition("direction", ["axial"], 3), condition("additional", ["phase-180-coupling"], 4), condition("history", ["after-repair", "after-alignment"], 2)], ["Проверить центровку", "Осмотреть муфту", "Сравнить фазу по обе стороны муфты"], ["vibration-spectrum-1x-2x"]),
  rule("angular-misalignment", "vibration-fault-angular-misalignment", "Угловая несоосность", [condition("frequencies", ["one-two-x", "dominant-2x"], 4), condition("direction", ["axial"], 3), condition("additional", ["axial-antiphase", "phase-180-coupling"], 4)], ["Проверить угловую центровку", "Проверить муфту и осевой зазор"], ["vibration-spectrum-2x"]),
  rule("resonance", "vibration-fault-resonance", "Резонанс", [condition("frequencies", ["constant-frequency"], 4), condition("history", ["speed-band"], 4), condition("additional", ["resonance-phase-jump"], 4), condition("signs", ["one-x"], 1)], ["Выполнить анализ разгона и выбега", "Проверить фазовый скачок", "Определить собственную частоту"], ["vibration-spectrum-resonance"], ["Резонанс конструкции можно перепутать с нестабильностью масляного клина."]),
  rule("looseness", "vibration-fault-mechanical-looseness", "Механическое ослабление", [condition("frequencies", ["harmonic-series", "half-x", "third-x"], 4), condition("signs", ["higher-harmonics", "subharmonics"], 2), condition("additional", ["impacts"], 2)], ["Проверить крепёж, посадки и фундамент", "Сопоставить вибрацию соседних точек"], ["vibration-spectrum-harmonic-series", "vibration-spectrum-half"]),
  rule("rub", "vibration-fault-rub", "Задевание вращающихся частей", [condition("frequencies", ["half-x", "third-x", "harmonic-series"], 4), condition("additional", ["impacts", "orbit-loops", "reverse-precession"], 3)], ["Проверить зазоры", "Осмотреть орбиту и временной сигнал"], ["vibration-spectrum-half", "vibration-spectrum-third"]),
  rule("oil-whirl", "vibration-fault-oil-whirl", "Нестабильность масляного клина", [condition("construction", ["journal-bearing"], 3, true), condition("frequencies", ["oil-whirl"], 5), condition("operatingMode", ["runup", "coastdown"], 2), condition("history", ["temperature-dependent"], 2)], ["Проверить положение вала", "Проверить температуру и давление масла", "Сопоставить с нагрузкой и разгоном/выбегом"], ["vibration-spectrum-oil-whirl"], ["Нестабильность масляного клина следует отличать от резонанса конструкции."]),
  rule("precession", "vibration-fault-rotor-precession", "Прецессия ротора", [condition("construction", ["journal-bearing"], 3, true), condition("frequencies", ["oil-whirl", "subsynchronous"], 5), condition("additional", ["reverse-precession", "orbit-change"], 3)], ["Проверить орбиту и положение вала", "Проверить параметры системы смазки"], ["vibration-spectrum-oil-whirl"]),
  rule("cavitation", "vibration-fault-cavitation", "Кавитация", [condition("equipment", ["pump", "pump-unit"], 3, true), condition("signs", ["broadband"], 4), condition("signs", ["unusual-noise", "performance-loss"], 2), condition("history", ["load-dependent"], 2)], ["Проверить давление на всасывании", "Проверить расход и режим работы", "Исключить препятствие в проточной части"], ["vibration-spectrum-cavitation", "vibration-spectrum-broadband-noise"]),
  rule("rolling-bearing", "vibration-fault-bearing-outer-race", "Повреждение подшипника качения", [condition("construction", ["rolling-bearing"], 2), condition("signs", ["impulses"], 5), condition("frequencies", ["bearing-frequencies"], 4), condition("additional", ["impacts"], 2)], ["Проверить огибающую и частоты подшипника", "Проверить смазку и посадку", "Повторить измерение с надёжным креплением датчика"], ["vibration-spectrum-bpfo", "vibration-spectrum-impulse"]),
  rule("lubrication", "vibration-fault-lubrication", "Нарушение смазки", [condition("signs", ["impulses", "bearing-heat"], 3), condition("construction", ["rolling-bearing"], 2), condition("history", ["temperature-dependent"], 2)], ["Проверить количество и состояние смазки", "Сопоставить температуру и высокочастотную вибрацию"], ["vibration-spectrum-broadband-noise"]),
  rule("gears", "vibration-fault-gears", "Дефект зубчатой передачи", [condition("construction", ["gears"], 2, true), condition("frequencies", ["gear-mesh", "sidebands"], 5), condition("history", ["load-dependent"], 2)], ["Осмотреть зубчатое зацепление", "Проверить боковые полосы и зависимость от нагрузки"], ["vibration-spectrum-gear-mesh", "vibration-spectrum-sidebands"]),
  rule("motor-electrical", "vibration-fault-motor-electrical", "Электромагнитная неисправность двигателя", [condition("equipment", ["motor", "pump-unit", "generator"], 2, true), condition("frequencies", ["constant-frequency", "sidebands"], 3), condition("signs", ["unknown-frequency"], 2)], ["Проверить ток, напряжение и воздушный зазор", "Сопоставить частоты с электрическими параметрами"], [], ["Вывод нельзя подтверждать без анализа электрических параметров."]),
  rule("soft-foot", "vibration-fault-soft-foot", "Мягкая опора", [condition("frequencies", ["one-two-x", "harmonic-series"], 2), condition("history", ["after-repair", "after-alignment"], 3), condition("location", ["foundation"], 3)], ["Проверить прилегание и затяжку опор", "Повторить центровку после устранения мягкой опоры"])
]);
