import { content } from "./dom.js";
import { isFavorite, toggleFavorite } from "./favorites.js";
import { escapeAttribute, safeText } from "./html.js";
import { getRouteHash, goBack, navigate } from "./router.js";
import { getArticles, getItem, getItemRoute } from "./store.js";
import { getVibrationKnowledgeBlocks } from "./vibrationKnowledge.js";
import { APP_VERSION } from "./pwaConfig.js";
import { formatCalculation } from "./vibrationCalculations.js";
import { saveToolTransfer } from "./vibrationCalculatorStorage.js";
import { compareMeasurements, createBackup, createId, describeTrend, groupComparableMeasurements, measurementsToCsv, normalizeMeasurement, parseMeasurementsCsv, routeProgress, trendStatistics, validateBackup } from "./vibrationJournalCore.js";
import { clearJournalData, countJournalRecords, deleteJournalRecord, exportJournalData, getJournalRecord, importJournalData, listJournalRecords, putJournalRecord, relatedCounts } from "./vibrationJournalDb.js";
import { renderTrendChart } from "./vibrationJournalChart.js";

export const VIBRATION_JOURNAL_TOOL_ID = "vibration-tool-trend-log";
let article;
let journalState = { view: "home", id: null, parent: null };

const equipmentTypes = ["насос", "электродвигатель", "насосный агрегат", "вентилятор", "дымосос", "компрессор", "редуктор", "турбина", "генератор", "центрифуга", "вертикальная машина", "другое оборудование"];
const nodeTypes = ["приводной подшипник", "неприводной подшипник", "муфта", "корпус", "фундамент", "редуктор", "вал", "рабочее колесо", "подшипник насоса", "подшипник двигателя", "другое"];
const directions = ["горизонтальное", "вертикальное", "осевое", "радиальное", "тангенциальное", "относительное перемещение вала по каналу X", "относительное перемещение вала по каналу Y", "другое"];
const eventTypes = ["ремонт", "замена подшипника", "центровка", "балансировка", "замена муфты", "изменение трубопровода", "изменение фундамента", "изменение режима", "смазка", "очистка", "аварийная остановка", "пуск", "другое"];
const amplitudeTypes = ["RMS", "Peak", "Peak-to-Peak", "неизвестно", "неприменимо"];

const input = (name, label, value = "", options = "") => `<label class="journal-field"><span>${label}</span><input name="${name}" value="${escapeAttribute(value)}" ${options}><small data-error="${name}"></small></label>`;
const select = (name, label, values, current = "") => `<label class="journal-field"><span>${label}</span><select name="${name}">${values.map(entry => { const [value, text] = Array.isArray(entry) ? entry : [entry, entry]; return `<option value="${escapeAttribute(value)}" ${value === current ? "selected" : ""}>${safeText(text)}</option>`; }).join("")}</select><small data-error="${name}"></small></label>`;
const textarea = (name, label, value = "") => `<label class="journal-field journal-field-wide"><span>${label}</span><textarea name="${name}" rows="3">${safeText(value)}</textarea></label>`;

function header(title, subtitle = "Журнал виброизмерений") {
  return `<div class="page-header"><button class="back-button" id="back-button" aria-label="Вернуться">‹</button><div><h2 tabindex="-1">${safeText(title)}</h2><p>${safeText(subtitle)}</p></div></div>`;
}

function warning() { return `<aside class="journal-warning"><strong>Важно</strong><p>Журнал предназначен для хранения и сравнения результатов измерений. Изменение тренда является диагностическим признаком, но само по себе не устанавливает неисправность и не определяет допустимость дальнейшей эксплуатации оборудования.</p></aside>`; }

async function setView(view, id = null, parent = null) { journalState = { view, id, parent }; await renderCurrent(); }

function bindBack(fallback) { content.querySelector("#back-button").addEventListener("click", fallback); }

function card(record, type, subtitle) {
  return `<button class="journal-card" type="button" data-open-type="${type}" data-open-id="${escapeAttribute(record.id)}"><span class="article-category">${safeText(subtitle)}</span><strong>${safeText(record.name || record.title || record.code)}</strong>${record.description ? `<small>${safeText(record.description)}</small>` : ""}${record.status === "archived" ? `<em>Архив</em>` : ""}</button>`;
}

function bindCards() { content.querySelectorAll("[data-open-type]").forEach(button => button.addEventListener("click", () => setView(button.dataset.openType, button.dataset.openId, journalState))); }

function openDialog(title, body, submitLabel, onSubmit) {
  const dialog = document.createElement("dialog"); dialog.className = "journal-dialog";
  dialog.innerHTML = `<form method="dialog"><div class="journal-dialog-heading"><h3>${safeText(title)}</h3><button type="button" aria-label="Закрыть" data-close>×</button></div><div class="journal-form-grid">${body}</div><div class="journal-form-error" role="alert"></div><div class="journal-actions"><button type="submit">${safeText(submitLabel)}</button><button type="button" class="secondary-button" data-close>Отмена</button></div></form>`;
  document.body.append(dialog); dialog.showModal();
  dialog.querySelectorAll("[data-close]").forEach(button => button.addEventListener("click", () => dialog.close()));
  dialog.addEventListener("close", () => dialog.remove());
  dialog.querySelector("form").addEventListener("submit", async event => { event.preventDefault(); const form = event.currentTarget; try { await onSubmit(Object.fromEntries(new FormData(form).entries()), form); dialog.close(); await renderCurrent(); } catch (error) { dialog.querySelector(".journal-form-error").textContent = error.message; } });
}

async function renderHome() {
  const [objects, unitsCount, pointsCount, measurementCount, recentMeasurements, recentEvents, routes] = await Promise.all([
    listJournalRecords("objects", { limit: 200 }), countJournalRecords("units"), countJournalRecords("points"), countJournalRecords("measurements"),
    listJournalRecords("measurements", { index: "measuredAt", direction: "prev", limit: 5 }), listJournalRecords("events", { index: "occurredAt", direction: "prev", limit: 5 }), listJournalRecords("routes", { index: "status", value: "active", limit: 1 })
  ]);
  const favorite = isFavorite("vibration", article.id);
  content.innerHTML = `${header("Журнал виброизмерений", "Локальный журнал и анализ трендов")}<article class="journal-page">${warning()}<section class="journal-toolbar"><button data-add-object>Добавить объект</button><button data-quick>Быстрое измерение</button><button data-start-route>Начать маршрут</button><button class="secondary-button" data-import>Импорт</button><button class="secondary-button" data-export>Экспорт</button><button class="favorite-button ${favorite ? "active" : ""}" data-favorite aria-pressed="${favorite}">${favorite ? "★" : "☆"}</button></section><label class="journal-search"><span>Поиск в журнале</span><input type="search" data-search placeholder="Объект, агрегат, точка или событие"><button type="button" data-reset-search>Сбросить фильтры</button></label><section class="journal-stats"><div><strong>${objects.length}</strong><span>объектов</span></div><div><strong>${unitsCount}</strong><span>агрегатов</span></div><div><strong>${pointsCount}</strong><span>точек</span></div><div><strong>${measurementCount}</strong><span>измерений</span></div></section>${routes[0] ? routeDraftCard(routes[0]) : ""}<section><h3>Объекты</h3><div class="journal-card-list" data-object-list>${objects.length ? objects.map(object => card(object, "object", object.site || "Объект")).join("") : `<div class="journal-empty">Добавьте первый объект, затем агрегат и измерительные точки.</div>`}</div></section><section class="journal-columns"><div><h3>Последние измерения</h3>${recentMeasurements.length ? recentMeasurements.map(item => `<button class="journal-row" data-open-type="point" data-open-id="${item.pointId}"><span>${new Date(item.measuredAt).toLocaleString("ru-RU")}</span><strong>${formatCalculation(item.value)} ${safeText(item.unit)}</strong></button>`).join("") : `<p class="journal-muted">Записей пока нет.</p>`}</div><div><h3>Последние события</h3>${recentEvents.length ? recentEvents.map(item => `<div class="journal-row"><span>${new Date(item.occurredAt).toLocaleDateString("ru-RU")}</span><strong>${safeText(item.title)}</strong></div>`).join("") : `<p class="journal-muted">Событий пока нет.</p>`}</div></section><aside class="journal-backup-note"><strong>Резервное копирование</strong><p>Данные журнала хранятся только на этом устройстве. Регулярно создавайте резервную копию.</p><button data-export-json>Скачать JSON</button><button class="danger-button" data-clear-all>Удалить все данные</button></aside></article>`;
  bindBack(() => goBack({ view: "section", method: "vibration", itemId: "vibration-tools" })); bindCards();
  content.querySelector("[data-add-object]").addEventListener("click", addObjectDialog);
  content.querySelector("[data-favorite]").addEventListener("click", event => { const on = toggleFavorite("vibration", article.id); event.currentTarget.textContent = on ? "★" : "☆"; event.currentTarget.setAttribute("aria-pressed", String(on)); });
  content.querySelector("[data-search]").addEventListener("input", event => { const query = event.target.value.toLocaleLowerCase("ru-RU"); content.querySelectorAll("[data-object-list] .journal-card").forEach(item => item.hidden = !item.textContent.toLocaleLowerCase("ru-RU").includes(query)); });
  content.querySelector("[data-reset-search]").addEventListener("click", () => { content.querySelector("[data-search]").value = ""; content.querySelectorAll("[data-object-list] .journal-card").forEach(item => item.hidden = false); });
  content.querySelectorAll("[data-export],[data-export-json]").forEach(button => button.addEventListener("click", exportDialog));
  content.querySelector("[data-import]").addEventListener("click", importDialog);
  content.querySelector("[data-quick]").addEventListener("click", quickMeasurementDialog);
  content.querySelector("[data-start-route]").addEventListener("click", startRouteDialog);
  content.querySelector("[data-clear-all]").addEventListener("click", clearAll);
  content.querySelector("[data-resume-route]")?.addEventListener("click", event => setView("route", event.currentTarget.dataset.resumeRoute));
}

function addObjectDialog() { openDialog("Новый объект", `${input("name", "Название *", "", "required")}${input("site", "Площадка или подразделение")}${textarea("description", "Описание и заметки")}`, "Сохранить", data => putJournalRecord("objects", { ...data, status: "active" })); }

async function renderObject(id) {
  const object = await getJournalRecord("objects", id); if (!object) return setView("home");
  const units = await listJournalRecords("units", { index: "objectId", value: id, limit: 500 });
  content.innerHTML = `${header(object.name, "Объект · Журнал виброизмерений")}<article class="journal-page"><section class="journal-toolbar"><button data-add-unit>Добавить агрегат</button><button class="secondary-button" data-edit>Редактировать</button><button class="secondary-button" data-archive>${object.status === "archived" ? "Восстановить" : "Архивировать"}</button><button class="danger-button" data-delete>Удалить</button></section><p>${safeText(object.description || "Описание не указано.")}</p><section><h3>Агрегаты</h3><div class="journal-card-list">${units.length ? units.map(unit => card(unit, "unit", unit.equipmentType)).join("") : `<div class="journal-empty">Добавьте агрегат.</div>`}</div></section></article>`;
  bindBack(() => setView("home")); bindCards();
  content.querySelector("[data-add-unit]").addEventListener("click", () => openDialog("Новый агрегат", `${input("name", "Название *", "", "required")}${select("equipmentType", "Тип оборудования", equipmentTypes)}${input("inventoryNumber", "Инвентарный или заводской номер")}${input("manufacturer", "Изготовитель")}${input("model", "Модель")}${input("nominalRpm", "Номинальные обороты", "", "inputmode='decimal'")}${textarea("description", "Описание")}`, "Сохранить", data => putJournalRecord("units", { ...data, objectId: id, status: "active" })));
  bindEntityActions("objects", object, { name: "Название", description: "Описание" });
}

async function renderUnit(id) {
  const unit = await getJournalRecord("units", id); if (!unit) return setView("home"); const object = await getJournalRecord("objects", unit.objectId);
  const [nodes, events] = await Promise.all([listJournalRecords("nodes", { index: "unitId", value: id, limit: 500 }), listJournalRecords("events", { index: "unitId", value: id, limit: 100 })]);
  content.innerHTML = `${header(unit.name, `${object?.name || "Объект"} · ${unit.equipmentType}`)}<article class="journal-page"><section class="journal-toolbar"><button data-add-node>Добавить узел</button><button data-add-event>Добавить событие</button><button data-summary>Скопировать сводку</button><button class="secondary-button" data-edit>Редактировать</button><button class="secondary-button" data-archive>${unit.status === "archived" ? "Восстановить" : "Архивировать"}</button><button class="danger-button" data-delete>Удалить</button></section><section class="journal-unit-info"><span>Номер: ${safeText(unit.inventoryNumber || "не указан")}</span><span>Модель: ${safeText(unit.model || "не указана")}</span><span>Номинальные обороты: ${safeText(unit.nominalRpm || "не указаны")}</span></section><section><h3>Узлы и точки</h3><div class="journal-card-list">${nodes.length ? nodes.map(node => card(node, "node", node.nodeType)).join("") : `<div class="journal-empty">Добавьте узел оборудования.</div>`}</div></section><section><h3>События</h3>${events.length ? events.sort((a,b)=>new Date(b.occurredAt)-new Date(a.occurredAt)).map(event => `<div class="journal-row"><span>${new Date(event.occurredAt).toLocaleString("ru-RU")}</span><strong>${safeText(event.title)}</strong><small>${safeText(event.description)}</small></div>`).join("") : `<p class="journal-muted">Событий нет.</p>`}</section></article>`;
  bindBack(() => setView("object", unit.objectId)); bindCards();
  content.querySelector("[data-add-node]").addEventListener("click", () => openDialog("Новый узел", `${input("name", "Название *", "", "required")}${select("nodeType", "Тип узла", nodeTypes)}${input("sequence", "Порядковый номер")}${textarea("description", "Описание")}`, "Сохранить", data => putJournalRecord("nodes", { ...data, unitId: id })));
  content.querySelector("[data-add-event]").addEventListener("click", () => eventDialog(id));
  content.querySelector("[data-summary]").addEventListener("click", () => copyUnitSummary(unit, object, nodes, events));
  bindEntityActions("units", unit, { name: "Название", description: "Описание" });
}

async function renderNode(id) {
  const node = await getJournalRecord("nodes", id); if (!node) return setView("home"); const unit = await getJournalRecord("units", node.unitId);
  const points = await listJournalRecords("points", { index: "nodeId", value: id, limit: 1000 });
  content.innerHTML = `${header(node.name, `${unit?.name || "Агрегат"} · ${node.nodeType}`)}<article class="journal-page"><section class="journal-toolbar"><button data-add-point>Добавить точку</button><button class="secondary-button" data-edit>Редактировать</button><button class="danger-button" data-delete>Удалить</button></section><section><h3>Измерительные точки</h3><div class="journal-card-list">${points.length ? points.map(point => card({ ...point, name: `${point.code} — ${point.name}` }, "point", point.direction)).join("") : `<div class="journal-empty">Добавьте измерительную точку.</div>`}</div></section></article>`;
  bindBack(() => setView("unit", node.unitId)); bindCards();
  content.querySelector("[data-add-point]").addEventListener("click", () => pointDialog(id));
  bindEntityActions("nodes", node, { name: "Название", description: "Описание" }, false);
}

function pointDialog(nodeId, source = {}) {
  openDialog(source.id ? "Редактировать точку" : "Новая измерительная точка", `${input("code", "Код точки *", source.code || "", "required")}${input("name", "Название *", source.name || "", "required")}${select("direction", "Направление", directions, source.direction)}${select("defaultParameter", "Параметр", ["Виброскорость", "Виброускорение", "Виброперемещение", "Относительное перемещение вала", "Другое"], source.defaultParameter)}${input("defaultUnit", "Единица", source.defaultUnit || "мм/с")}${input("amplitudeType", "Тип значения", source.amplitudeType || "RMS")}${input("sensorType", "Тип датчика", source.sensorType || "")}${input("mounting", "Способ установки", source.mounting || "")}${input("frequencyRange", "Частотный диапазон", source.frequencyRange || "")}${textarea("note", "Примечание", source.note || "")}`, "Сохранить", data => putJournalRecord("points", { ...source, ...data, nodeId, status: source.status || "active" }));
}

async function renderPoint(id) {
  const point = await getJournalRecord("points", id); if (!point) return setView("home"); const node = await getJournalRecord("nodes", point.nodeId); const unit = await getJournalRecord("units", node.unitId);
  const [measurements, events, limits] = await Promise.all([listJournalRecords("measurements", { index: "pointId", value: id, limit: 1000 }), listJournalRecords("events", { index: "unitId", value: unit.id, limit: 200 }), listJournalRecords("limits", { index: "pointId", value: id, limit: 20 })]);
  const groups = groupComparableMeasurements(measurements); const primary = groups.sort((a,b)=>b.items.length-a.items.length)[0]?.items || []; const stats = trendStatistics(primary); const trend = describeTrend(stats, primary, events);
  content.innerHTML = `${header(`${point.code} — ${point.name}`, `${unit.name} · ${node.name}`)}<article class="journal-page"><section class="journal-toolbar"><button data-add-measurement>Добавить измерение</button><button data-duplicate>Дублировать точку</button><button data-assistant>Открыть помощник</button><button data-calculator>Калькуляторы</button><button class="secondary-button" data-edit-point>Редактировать</button></section><section class="journal-point-meta"><span>${safeText(point.direction)}</span><span>${safeText(point.defaultParameter)} · ${safeText(point.defaultUnit)}</span><span>${safeText(point.sensorType || "датчик не указан")}</span></section><section class="journal-trend"><div class="journal-section-heading"><div><span class="article-category">Анализ тренда</span><h3>${safeText(trend.label)}</h3></div><label><input type="checkbox" data-toggle-events checked> События</label></div><div data-chart>${renderTrendChart(primary, events)}</div>${stats ? statsCards(stats) : ""}${groups.length > 1 ? `<aside class="journal-warning">Найдено ${groups.length} несопоставимых серий. RMS, Peak, разные параметры или частотные диапазоны не объединены одной линией.</aside>` : ""}</section><section><div class="journal-section-heading"><h3>Измерения</h3><button data-compare>Сравнить записи</button></div><div class="journal-measurement-list">${measurements.length ? measurements.sort((a,b)=>new Date(b.measuredAt)-new Date(a.measuredAt)).map(item => measurementRow(item)).join("") : `<div class="journal-empty">Добавьте минимум два сопоставимых измерения для тренда.</div>`}</div></section><section><h3>Пользовательские границы</h3><button data-add-limit>Добавить границу</button>${limits.map(limit => `<div class="journal-row"><strong>${safeText(limit.name)}: ${formatCalculation(limit.value)} ${safeText(limit.unit)}</strong><span>${safeText(limit.source || "Источник границы не указан.")}</span></div>`).join("")}</section><section class="journal-related">${relatedMaterials(point, unit)}</section><aside class="journal-attachments">Вложения — в разработке</aside></article>`;
  bindBack(() => setView("node", point.nodeId));
  const periodLabel = document.createElement("label"); periodLabel.className = "journal-period"; periodLabel.innerHTML = `<span>Период</span><select aria-label="Период тренда"><option value="7">7 дней</option><option value="30">30 дней</option><option value="90">90 дней</option><option value="183">6 месяцев</option><option value="365">1 год</option><option value="all" selected>Всё время</option></select>`;
  content.querySelector(".journal-section-heading").append(periodLabel);
  periodLabel.querySelector("select").addEventListener("change", event => { const days = event.target.value; const cutoff = days === "all" ? -Infinity : Date.now() - Number(days) * 86400000; const filtered = primary.filter(item => new Date(item.measuredAt).getTime() >= cutoff); content.querySelector("[data-chart]").innerHTML = renderTrendChart(filtered, events, { showEvents: content.querySelector("[data-toggle-events]").checked }); });
  const archiveButton = document.createElement("button"); archiveButton.type = "button"; archiveButton.className = "secondary-button"; archiveButton.textContent = point.status === "archived" ? "Восстановить" : "Архивировать";
  archiveButton.addEventListener("click", async () => { await putJournalRecord("points", { ...point, status: point.status === "archived" ? "active" : "archived" }); await renderCurrent(); });
  const deleteButton = document.createElement("button"); deleteButton.type = "button"; deleteButton.className = "danger-button"; deleteButton.textContent = "Удалить";
  deleteButton.addEventListener("click", async () => { const counts = await relatedCounts("points", point.id); const total = Object.values(counts).reduce((a,b)=>a+b,0); if (total) return alert(`Удаление невозможно: связано записей ${total}. Сначала архивируйте точку или экспортируйте данные.`); if (confirm("Окончательно удалить точку?")) { await deleteJournalRecord("points", point.id); await setView("node", point.nodeId); } });
  content.querySelector(".journal-toolbar").append(archiveButton, deleteButton);
  content.querySelector("[data-add-measurement]").addEventListener("click", () => measurementDialog(point, unit));
  content.querySelector("[data-edit-point]").addEventListener("click", () => pointDialog(point.nodeId, point));
  content.querySelector("[data-duplicate]").addEventListener("click", () => pointDialog(point.nodeId, { ...point, id: "", code: `${point.code}-копия`, name: `${point.name} (копия)` }));
  content.querySelector("[data-toggle-events]").addEventListener("change", event => { content.querySelector("[data-chart]").innerHTML = renderTrendChart(primary, events, { showEvents: event.target.checked }); });
  content.querySelector("[data-compare]").addEventListener("click", () => compareDialog(measurements));
  content.querySelector("[data-assistant]").addEventListener("click", () => transferToAssistant(point, unit, primary));
  content.querySelector("[data-calculator]").addEventListener("click", () => calculatorDialog(point, primary.at(-1)));
  content.querySelector("[data-add-limit]").addEventListener("click", () => limitDialog(point));
  content.querySelectorAll("[data-edit-measurement]").forEach(button => button.addEventListener("click", () => { const item = measurements.find(value => value.id === button.dataset.editMeasurement); measurementDialog(point, unit, item); }));
}

function statsCards(stats) { return `<div class="journal-stats"><div><strong>${formatCalculation(stats.minimum)}</strong><span>минимум</span></div><div><strong>${formatCalculation(stats.maximum)}</strong><span>максимум</span></div><div><strong>${formatCalculation(stats.average)}</strong><span>среднее</span></div><div><strong>${formatCalculation(stats.median)}</strong><span>медиана</span></div><div><strong>${formatCalculation(stats.absoluteChange)}</strong><span>изменение</span></div><div><strong>${stats.relativeChange == null ? "—" : `${formatCalculation(stats.relativeChange)} %`}</strong><span>относительно первого</span></div></div>`; }
function measurementRow(item) { return `<label class="journal-measurement"><input type="checkbox" value="${item.id}" data-compare-item><span>${new Date(item.measuredAt).toLocaleString("ru-RU")}</span><strong>${formatCalculation(item.value)} ${safeText(item.unit)} · ${safeText(item.amplitudeType)}</strong><small>${safeText(item.operatingMode || "режим не указан")} · ${item.rpm ? `${safeText(item.rpm)} об/мин` : "обороты не указаны"}</small><button type="button" data-edit-measurement="${item.id}">Редактировать</button></label>`; }

function measurementDialog(point, unit, source = {}) {
  const now = new Date(); now.setMinutes(now.getMinutes() - now.getTimezoneOffset());
  openDialog(source.id ? "Редактировать измерение" : "Новое измерение", `${input("measuredAt", "Дата и время *", source.measuredAt?.slice(0,16) || now.toISOString().slice(0,16), "type='datetime-local' required")}${input("parameter", "Параметр *", source.parameter || point.defaultParameter, "required")}${input("value", "Значение *", source.value ?? "", "inputmode='decimal' required")}${input("unit", "Единица *", source.unit || point.defaultUnit, "required")}${select("amplitudeType", "Тип амплитуды", amplitudeTypes, source.amplitudeType || point.amplitudeType)}${input("frequencyRange", "Частотный диапазон", source.frequencyRange || point.frequencyRange)}${input("rpm", "Обороты, об/мин", source.rpm || unit.nominalRpm || "", "inputmode='decimal'")}${input("load", "Нагрузка", source.load || "")}${input("temperature", "Температура", source.temperature || "", "inputmode='decimal'")}${input("pressure", "Давление", source.pressure || "")}${input("flow", "Расход", source.flow || "")}${input("operatingMode", "Режим работы", source.operatingMode || "")}${textarea("note", "Примечание", source.note || "")}${input("spectral", "Составляющие: обозначение=Гц, через запятую", (source.spectralComponents || []).map(x=>`${x.designation}=${x.frequencyHz}`).join(", "))}`, "Сохранить", async data => {
    const normalized = normalizeMeasurement({ ...source, ...data, pointId: point.id, measuredAt: new Date(data.measuredAt).toISOString(), source: source.source || "ручной ввод" });
    const saved = await putJournalRecord("measurements", normalized);
    if (data.spectral.trim()) for (const pair of data.spectral.split(",")) { const [designation, frequency] = pair.split("="); if (designation?.trim() && frequency?.trim()) await putJournalRecord("spectralComponents", { measurementId: saved.id, designation: designation.trim(), frequencyHz: Number(frequency.trim().replace(",", ".")) }); }
  });
}

function eventDialog(unitId) { const now = new Date(); now.setMinutes(now.getMinutes()-now.getTimezoneOffset()); openDialog("Новое событие", `${input("occurredAt", "Дата и время *", now.toISOString().slice(0,16), "type='datetime-local' required")}${select("eventType", "Тип события", eventTypes)}${input("title", "Название *", "", "required")}${textarea("description", "Описание")}`, "Сохранить", data => putJournalRecord("events", { ...data, unitId, occurredAt: new Date(data.occurredAt).toISOString() })); }
function limitDialog(point) { openDialog("Пользовательская граница", `${input("name", "Название *", "Уровень наблюдения", "required")}${input("value", "Значение *", "", "inputmode='decimal' required")}${input("unit", "Единица", point.defaultUnit)}${input("amplitudeType", "Тип амплитуды", point.amplitudeType)}${input("frequencyRange", "Частотный диапазон", point.frequencyRange)}${input("source", "Источник")}${textarea("note", "Примечание")}`, "Сохранить", data => putJournalRecord("limits", { ...data, pointId: point.id, value: Number(data.value.replace(",", ".")), setAt: new Date().toISOString() })); }

function compareDialog(measurements) {
  const ids = [...content.querySelectorAll("[data-compare-item]:checked")].map(input => input.value); const selected = ids.map(id => measurements.find(item => item.id === id)).filter(Boolean);
  try { const compared = compareMeasurements(selected); const base = compared[0]; openDialog("Сравнение записей", `<div class="journal-compare journal-field-wide"><table><thead><tr><th>Дата</th><th>Значение</th><th>Изменение</th><th>Обороты</th><th>Температура</th></tr></thead><tbody>${compared.map(item => `<tr><td>${new Date(item.measuredAt).toLocaleString("ru-RU")}</td><td>${formatCalculation(item.value)} ${safeText(item.unit)}</td><td>${formatCalculation(item.absoluteChange)} ${safeText(item.normalizedUnit)}${item.relativeChange == null ? "" : ` (${formatCalculation(item.relativeChange)} %)`}</td><td>${safeText(item.rpm || "—")}</td><td>${safeText(item.temperature || "—")}</td></tr>`).join("")}</tbody></table><p>Базовая запись: ${new Date(base.measuredAt).toLocaleString("ru-RU")}. Различия рабочих условий необходимо учитывать отдельно.</p></div>`, "Закрыть", async () => {}); } catch (error) { alert(error.message); }
}

async function quickMeasurementDialog() {
  const points = await listJournalRecords("points", { limit: 5000 });
  if (!points.length) return alert("Сначала создайте измерительную точку.");
  openDialog("Быстрое измерение", `${select("pointId", "Точка", points.map(point => `${point.id}|${point.code} — ${point.name}`))}${input("value", "Значение *", "", "inputmode='decimal' required")}${input("measuredAt", "Дата и время", new Date().toISOString().slice(0,16), "type='datetime-local'")}${input("operatingMode", "Режим работы")}`, "Проверить и сохранить", async data => { const pointId = data.pointId.split("|")[0]; const point = points.find(item => item.id === pointId); const normalized = normalizeMeasurement({ pointId, value: data.value, measuredAt: new Date(data.measuredAt).toISOString(), parameter: point.defaultParameter, unit: point.defaultUnit, amplitudeType: point.amplitudeType || "неизвестно", frequencyRange: point.frequencyRange || "", operatingMode: data.operatingMode, source: "ручной ввод" }); await putJournalRecord("measurements", normalized); });
}

function bindEntityActions(store, record, fields, archivable = true) {
  content.querySelector("[data-edit]")?.addEventListener("click", () => openDialog("Редактировать", Object.entries(fields).map(([name,label]) => name === "description" ? textarea(name,label,record[name]) : input(name,label,record[name], name === "name" ? "required" : "")).join(""), "Сохранить", data => putJournalRecord(store, { ...record, ...data })));
  content.querySelector("[data-archive]")?.addEventListener("click", async () => { await putJournalRecord(store, { ...record, status: record.status === "archived" ? "active" : "archived" }); await renderCurrent(); });
  content.querySelector("[data-delete]")?.addEventListener("click", async () => { const counts = await relatedCounts(store, record.id); const total = Object.values(counts).reduce((a,b)=>a+b,0); if (total) return alert(`Удаление невозможно без явной обработки дочерних данных. Связано записей: ${total}. Используйте архивирование.`); if (confirm("Окончательно удалить запись?")) { await deleteJournalRecord(store, record.id); archivable ? await setView(store === "objects" ? "home" : store === "units" ? "object" : "unit", record.objectId || record.unitId) : await setView("unit", record.unitId); } });
}

function routeDraftCard(route) { const progress = routeProgress(route); return `<section class="journal-route-draft"><span class="article-category">Незавершённый маршрут</span><h3>${safeText(route.name)}</h3><p>${progress.completed} из ${progress.total} точек</p><progress max="${progress.total}" value="${progress.completed}"></progress><button data-resume-route="${route.id}">Продолжить</button></section>`; }

async function startRouteDialog() {
  const objects = await listJournalRecords("objects", { limit: 500 }); if (!objects.length) return alert("Сначала добавьте объект.");
  openDialog("Новый маршрут", `${input("name", "Название *", "Маршрутный обход", "required")}${select("objectId", "Объект", objects.map(object => `${object.id}|${object.name}`))}`, "Выбрать точки", async data => { const objectId = data.objectId.split("|")[0]; const units = await listJournalRecords("units", { index: "objectId", value: objectId, limit: 1000 }); const nodes = (await Promise.all(units.map(unit => listJournalRecords("nodes", { index: "unitId", value: unit.id, limit: 1000 })))).flat(); const points = (await Promise.all(nodes.map(node => listJournalRecords("points", { index: "nodeId", value: node.id, limit: 1000 })))).flat(); if (!points.length) throw new Error("У объекта нет измерительных точек."); const route = await putJournalRecord("routes", { name: data.name, objectId, pointIds: points.map(point => point.id), entries: {}, status: "active", currentIndex: 0, startedAt: new Date().toISOString() }); setTimeout(() => setView("route", route.id), 0); });
}

async function renderRoute(id) {
  const route = await getJournalRecord("routes", id); if (!route) return setView("home"); const progress = routeProgress(route); const index = Math.min(route.currentIndex || 0, Math.max(route.pointIds.length - 1, 0)); const point = await getJournalRecord("points", route.pointIds[index]); const last = (await listJournalRecords("measurements", { index: "pointId", value: point.id, direction: "prev", limit: 1 }))[0];
  content.innerHTML = `${header(route.name, `Точка ${index + 1} из ${progress.total}`)}<article class="journal-page"><section class="journal-route-progress"><progress max="${progress.total}" value="${progress.completed}"></progress><strong>${progress.completed} заполнено · ${progress.skipped} осталось</strong></section><section class="journal-route-point"><span class="article-category">${safeText(point.direction)}</span><h3>${safeText(point.code)} — ${safeText(point.name)}</h3><p>${safeText(point.defaultParameter)} · ${safeText(point.defaultUnit)}</p><p>Последнее значение: ${last ? `${formatCalculation(last.value)} ${safeText(last.unit)}, ${new Date(last.measuredAt).toLocaleString("ru-RU")}` : "нет данных"}</p><form data-route-entry>${input("value", "Текущее значение", route.entries?.[point.id]?.value || "", "inputmode='decimal'")}${input("rpm", "Обороты", route.entries?.[point.id]?.rpm || "", "inputmode='decimal'")}${input("temperature", "Температура", route.entries?.[point.id]?.temperature || "", "inputmode='decimal'")}${textarea("note", "Примечание", route.entries?.[point.id]?.note || "")}<div class="journal-actions"><button type="button" data-previous ${index === 0 ? "disabled" : ""}>Предыдущая</button><button type="submit">Сохранить и далее</button><button type="button" class="secondary-button" data-finish>Завершить частично</button><button type="button" class="danger-button" data-delete-route>Удалить черновик</button></div></form></section></article>`;
  bindBack(() => setView("home"));
  content.querySelector("[data-finish]").type = "submit";
  const saveEntry = async () => { const data = Object.fromEntries(new FormData(content.querySelector("[data-route-entry]")).entries()); const entries = { ...(route.entries || {}), [point.id]: data }; await putJournalRecord("routes", { ...route, entries }); return entries; };
  content.querySelector("[data-route-entry]").addEventListener("submit", async event => { event.preventDefault(); const entries = await saveEntry(); if (event.submitter?.dataset.finish !== undefined || index === route.pointIds.length - 1) { for (const pointId of route.pointIds) { const entry = entries[pointId]; if (!entry?.value) continue; const routePoint = await getJournalRecord("points", pointId); await putJournalRecord("measurements", normalizeMeasurement({ pointId, value: entry.value, parameter: routePoint.defaultParameter, unit: routePoint.defaultUnit, amplitudeType: routePoint.amplitudeType || "неизвестно", frequencyRange: routePoint.frequencyRange || "", rpm: entry.rpm, temperature: entry.temperature, note: entry.note, measuredAt: new Date().toISOString(), source: "маршрут" })); } await putJournalRecord("routes", { ...route, entries, status: "completed", completedAt: new Date().toISOString() }); alert(`Маршрут завершён: ${routeProgress({ ...route, entries }).completed} из ${progress.total} точек.`); return setView("home"); } await putJournalRecord("routes", { ...route, entries, currentIndex: index + 1 }); await renderRoute(id); });
  content.querySelector("[data-previous]").addEventListener("click", async () => { const entries = await saveEntry(); await putJournalRecord("routes", { ...route, entries, currentIndex: index - 1 }); await renderRoute(id); });
  content.querySelector("[data-delete-route]").addEventListener("click", async () => { if (confirm("Удалить черновик маршрута и введённые значения?")) { await deleteJournalRecord("routes", id); await setView("home"); } });
}

async function exportDialog() {
  const data = await exportJournalData();
  openDialog("Экспорт журнала", `${select("format", "Формат", ["JSON — резервная копия", "CSV — измерения"])}${select("delimiter", "Разделитель CSV", [";", ","])}`, "Скачать", async form => { if (form.format.startsWith("JSON")) download(`defectosng-journal-${Date.now()}.json`, JSON.stringify(createBackup(data, APP_VERSION), null, 2), "application/json"); else download(`defectosng-measurements-${Date.now()}.csv`, measurementsToCsv(await enrichMeasurements(data), form.delimiter), "text/csv;charset=utf-8"); });
}

async function enrichMeasurements(data) { const pointMap = new Map(data.points.map(x=>[x.id,x])); const nodeMap = new Map(data.nodes.map(x=>[x.id,x])); const unitMap = new Map(data.units.map(x=>[x.id,x])); const objectMap = new Map(data.objects.map(x=>[x.id,x])); return data.measurements.map(m => { const point=pointMap.get(m.pointId)||{}; const node=nodeMap.get(point.nodeId)||{}; const unit=unitMap.get(node.unitId)||{}; const object=objectMap.get(unit.objectId)||{}; return {...m,pointCode:point.code,direction:point.direction,nodeName:node.name,unitName:unit.name,objectName:object.name}; }); }
function download(name, text, type) { const blob = new Blob([text], { type }); const url = URL.createObjectURL(blob); const link = document.createElement("a"); link.href = url; link.download = name; link.click(); setTimeout(() => URL.revokeObjectURL(url), 1000); }

function importDialog() {
  const dialog = document.createElement("dialog"); dialog.className="journal-dialog"; dialog.innerHTML=`<form method="dialog"><h3>Импорт JSON или CSV</h3><p>Сначала файл будет проверен. CSV сопоставляется только с существующими кодами точек и не создаёт оборудование автоматически.</p><label class="journal-field"><span>Файл</span><input type="file" accept="application/json,.json,text/csv,.csv" required data-file></label>${select("delimiter","Разделитель CSV",[";",","])}${select("mode","Режим JSON",[["merge","объединить"],["replace","заменить"],["copy","импортировать как копию"]])}<div data-preview></div><div class="journal-actions"><button type="button" data-check>Проверить</button><button type="submit" disabled data-confirm>Импортировать</button><button type="button" class="secondary-button" data-close>Отмена</button></div></form>`; document.body.append(dialog); dialog.showModal(); let backup; let csvRows;
  dialog.querySelector("[data-close]").addEventListener("click",()=>dialog.close()); dialog.addEventListener("close",()=>dialog.remove());
  dialog.querySelector("[data-check]").addEventListener("click",async()=>{try{const file=dialog.querySelector("[data-file]").files[0]; if(!file)throw new Error("Выберите файл."); const text=await file.text(); if(file.name.toLowerCase().endsWith(".csv")){csvRows=parseMeasurementsCsv(text,dialog.querySelector("[name=delimiter]").value); backup=null; dialog.querySelector("[data-preview]").textContent=`Проверено строк CSV: ${csvRows.length}. Перед импортом будут проверены коды точек и числовые значения.`;}else{backup=JSON.parse(text);csvRows=null;const summary=validateBackup(backup);dialog.querySelector("[data-preview]").textContent=`Проверено: ${summary.objects} объектов, ${summary.units} агрегатов, ${summary.points} точек, ${summary.measurements} измерений, ${summary.events} событий.`;}dialog.querySelector("[data-confirm]").disabled=false;}catch(error){dialog.querySelector("[data-preview]").textContent=error.message;dialog.querySelector("[data-confirm]").disabled=true;}});
  dialog.querySelector("form").addEventListener("submit",async event=>{event.preventDefault(); if(backup){const mode=event.currentTarget.elements.mode.value;if(mode==="replace"&&!confirm("Заменить все текущие данные проверенной копией?"))return;await importJournalData(backup,mode);}else if(csvRows){const points=await listJournalRecords("points",{limit:100000});const byCode=new Map(points.map(point=>[point.code,point]));const errors=[];for(const row of csvRows){const point=byCode.get(row["Точка"]);if(!point){errors.push(`строка ${row.row}: точка ${row["Точка"]} не найдена`);continue;}try{await putJournalRecord("measurements",normalizeMeasurement({pointId:point.id,measuredAt:new Date(row["Дата"]).toISOString(),parameter:row["Параметр"],value:row["Исходное значение"],unit:row["Исходная единица"],amplitudeType:row["Тип амплитуды"]||"неизвестно",rpm:row["Обороты"]||"",load:row["Нагрузка"]||"",temperature:row["Температура"]||"",pressure:row["Давление"]||"",flow:row["Расход"]||"",operatingMode:row["Режим"]||"",note:row["Примечание"]||"",source:"импорт"}));}catch(error){errors.push(`строка ${row.row}: ${error.message}`);}}if(errors.length)alert(`Импорт завершён с замечаниями:\n${errors.slice(0,20).join("\n")}`);}else return;dialog.close();await renderCurrent();});
}

async function clearAll() { if (!confirm("Первое подтверждение: удалить все данные журнала на этом устройстве?")) return; if (!confirm("Второе подтверждение: действие необратимо без резервной копии. Продолжить?")) return; await clearJournalData(); await renderCurrent(); }

function transferToAssistant(point, unit, measurements) { const latest = measurements.at(-1); const payload = { target: "vibration-tool-fault-search", equipment: unit.equipmentType, point: point.code, direction: point.direction, parameter: latest?.parameter || point.defaultParameter, value: latest?.value, unit: latest?.unit || point.defaultUnit, rpm: latest?.rpm, load: latest?.load, temperature: latest?.temperature, history: measurements.slice(-5).map(item=>({date:item.measuredAt,value:item.value,unit:item.unit})) }; if (confirm(`Передать помощнику: ${point.code}, ${payload.parameter}, последнее значение ${payload.value ?? "не указано"} ${payload.unit}, обороты ${payload.rpm || "не указаны"}?`)) { saveToolTransfer(payload); navigate({ view:"article",method:"vibration",itemId:"vibration-tool-fault-search" }); } }
function calculatorDialog(point, latest) { openDialog("Открыть калькулятор", `${select("target","Инструмент",["vibration-tool-rotation-frequency|Оборотная частота","vibration-tool-harmonics|Гармоники","vibration-tool-bearing-frequencies|Частоты подшипника","vibration-tool-unit-conversion|Пересчёт вибрации"])}`, "Открыть", async data => { const target=data.target.split("|")[0]; saveToolTransfer({target,rpm:latest?.rpm,value:latest?.value,unit:latest?.unit,parameter:latest?.parameter||point.defaultParameter}); setTimeout(()=>navigate({view:"article",method:"vibration",itemId:target}),0); }); }

function relatedMaterials(point, unit) { const source={id:"journal-point",metadata:{materialType:"tool",equipment:[unit.equipmentType],measuredParameters:[point.defaultParameter],relatedArticles:["vibration-measurement-points","vibration-measurement-directions","vibration-trend-analysis"]}}; const blocks=getVibrationKnowledgeBlocks(source,getArticles("vibration"),4).filter(block=>block.items?.length&&typeof block.items[0]!=="string").slice(0,2); return `<h3>Связанные материалы</h3>${blocks.map(block=>`<div><strong>${safeText(block.title)}</strong>${block.items.map(item=>`<a href="${getRouteHash(getItemRoute("vibration",item))}">${safeText(item.title)}</a>`).join("")}</div>`).join("")}`; }

async function copyUnitSummary(unit, object, nodes, events) { const points=(await Promise.all(nodes.map(node=>listJournalRecords("points",{index:"nodeId",value:node.id,limit:1000})))).flat(); const lines=[]; for(const point of points){const last=(await listJournalRecords("measurements",{index:"pointId",value:point.id,direction:"prev",limit:2})); const change=last.length>1?Number(last[0].normalizedValue??last[0].value)-Number(last[1].normalizedValue??last[1].value):null; lines.push(`${point.code} — ${point.name}: ${last[0]?`${last[0].value} ${last[0].unit}, ${new Date(last[0].measuredAt).toLocaleString("ru-RU")}, изменение ${change==null?"не рассчитано":formatCalculation(change)}`:"нет измерений"}`);} const report=`Журнал виброизмерений\nОбъект: ${object?.name||""}\nАгрегат: ${unit.name}\nТип оборудования: ${unit.equipmentType}\nИнвентарный номер: ${unit.inventoryNumber||""}\nДата формирования: ${new Date().toLocaleString("ru-RU")}\nИзмерительные точки:\n${lines.map((line,i)=>`${i+1}. ${line}`).join("\n")}\nСобытия:\n${events.map(e=>`${new Date(e.occurredAt).toLocaleDateString("ru-RU")}: ${e.title}`).join("\n")}\nВажно: данная сводка содержит результаты измерений и не является заключением о техническом состоянии оборудования.`; try{await navigator.clipboard.writeText(report);alert("Сводка скопирована.");}catch{alert(report);} }

async function renderCurrent() { if (journalState.view === "home") return renderHome(); if (journalState.view === "object") return renderObject(journalState.id); if (journalState.view === "unit") return renderUnit(journalState.id); if (journalState.view === "node") return renderNode(journalState.id); if (journalState.view === "point") return renderPoint(journalState.id); if (journalState.view === "route") return renderRoute(journalState.id); }

export async function renderVibrationJournal(toolArticle) { article=toolArticle; journalState={view:"home",id:null,parent:null}; try{await renderCurrent();}catch(error){content.innerHTML=`${header("Журнал виброизмерений")}<div class="empty-state"><strong>Не удалось открыть локальную базу журнала.</strong><p>${safeText(error.message)}</p></div>`;bindBack(()=>goBack({view:"section",method:"vibration",itemId:"vibration-tools"}));} }
